# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Fintech' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fintech
  pod 'NVActivityIndicatorView'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch =>'alamofire5'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'
end
